name: app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0-100.2.beta

dependencies:
  flutter:
    sdk: flutter

  # 안정적인 백그라운드 실행을 위한 서비스 패키지
  flutter_background_service: ^5.0.1

  # 아이콘
  cupertino_icons: ^1.0.8

  # 라우팅
  go_router: ^14.0.0

  # 상태 관리
  flutter_riverpod: ^2.6.1

  # 권한 요청
  permission_handler: ^11.0.0

  # 카메라/이미지 선택
  image_picker: ^1.0.7

  # GPS, 위치 기반
  geolocator: ^13.0.0

  # 센서
  sensors_plus: ^5.0.0

  # 네트워크 요청
  http: ^1.2.0

  # 날짜/시간 포맷
  intl: ^0.19.0

  # QR 코드 스캔
  mobile_scanner: ^7.1.3

  # 차트 (활동량 분석)
  fl_chart: ^0.66.2

  # 소셜 로그인
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.0

  # 걸음 수 측정
  pedometer: ^4.0.1

  # 로컬 데이터 저장 (눈바디 사진 경로 등)
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2

  # SVG 이미지 사용 (소셜 로그인 버튼 등)
  flutter_svg: ^2.0.10+1
  flutter_dotenv: ^6.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_18pt-Regular.ttf
        - asset: assets/fonts/Inter_18pt-Bold.ttf
          weight: 700

